name = "June's 2024"
author = "Khazoda"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecd3b981c1c994d0581d6f96fd32c1736d09b86ad0ff7da87d438f62f071a15e"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
